# this is a reusable workflow that should be used in every <client>-pipeline repository
# refer to https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Deploy Data Pipeline
on: 
  workflow_call:
    inputs:
      test_input:
        description: 'tester'
        default: 'tester'
        required: true
        type: string
    secrets:
      test_secret:
        description: 'test secret'
        required: true
        
jobs:
  deploy_pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    name: Build and deploy the pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: tester step
        run: echo "this is a test"
        with:
          test_input: ${{ inputs.test_input }}
          test_secret: ${{ secrets.test_secret }}